# **1. 정규화(Normalize)**

* column 간에 다른 min, max 값을 가지고 있는 경우에 값의 척도를 균일화 하는 것을 말한다.
* 네이버 영화평점(1 ~ 10 점)
* 넷플릭스 영화평점(1 ~ 5 점)

In [1]:
movie = {'naver' : [2, 4, 6, 8, 10], 'netflix' : [1, 2, 3, 4, 5]}

In [2]:
import pandas as pd
movie = pd.DataFrame(data=movie)
movie

   naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
min_max_scaler = MinMaxScaler()
min_max_movie = min_max_scaler.fit_transform(movie)

In [5]:
pd.DataFrame(min_max_movie, columns=['naver', 'netflix'])

   naver  netflix
0   0.00     0.00
1   0.25     0.25
2   0.50     0.50
3   0.75     0.75
4   1.00     1.00